version: "3"
services:
  influx:
    build:
      dockerfile: Dockerfile.dev
      context: ./influx
  mongo:
    build:
      dockerfile: Dockerfile.dev
      context: ./mongo
  telegraf:
    build:
      dockerfile: Dockerfile.dev
      context: ./telegraf
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  broker:
    build:
      dockerfile: Dockerfile.dev
      context: ./broker
    ports:
      - "1885:1885"
      - "3003:3003"
    volumes:
      - /app/node_modules
    environment:
      - MQTT_PORT=1885
      - WS_PORT=3003
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - "8081:8081"
    environment:
      - npm_config_unsafe_perm=true
      - WS_PORT=3003
      - BACKEND=server
      - MQTT_URI=broker
    depends_on:
      - broker
      - server
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
